### PR TITLE
Remove unnecessary import Cocoa line

### PR DESCRIPTION
**Pull request by weyhan**
Hi,

I'm trying to use lua4swift in iOS projects and found that the VirtualMachine.swift file is importing Cocoa. I've look at the rest of the source and finds nothing requires Cocoa so I'm submitting this pull request to remove that import so lua4swift can be used on iOS.

One side question, has lua4swift ever been tested on iOS? Will there be any interest in supporting iOS?

### CODE REVIEW

**Comment by sdegutis** [comment]
@weyhan Is it a requirement of Swift 3 that enum cases need to be lower-case now?

**Comment by weyhan** [comment]
It's not really lower case but camel case with the initial character lower case. I'm not sure if it's a requirement but it is in the recommended by Apple. The migration tool does the case change automatically so at least Apple is strongly pushing for it.

**Comment by robotoad** [comment]
It's part of the Swift 3 naming guidelines.

**Comment by weyhan** [comment]
@sdegutis Assuming my changes are okay, do you prefer to pull both commit for removing the import Cocoa line and Swift 3 conversion or pull them in 2 different pull request?

If you like to combine them, I can change the title for this pull request.

**Pull request merged**
